<template>
  <AdminLayout>
    <div class="admin-employee">
      <div>
        <AppSearch />
        <button id="add-button">Add</button>
      </div>
      <AppTable :headers="headers" :content="content" />
    </div>
  </AdminLayout>
</template>

<script>
import AdminLayout from "@/layouts/AdminLayout.vue";
import AppSearch from "@/components/AppSearch.vue";
import AppTable from "@/components/AppTable.vue";

export default {
  name: "AdminEmployees",
  components: {
    AdminLayout,
    AppSearch,
    AppTable,
  },
  data() {
    return {
      headers: [
        "ID",
        "NOMBRE",
        "CORREO",
        "CELULAR",
        "CÉDULA",
        "CARGO",
        "ACCIONES",
        "CORREO",
        "CELULAR",
        "CÉDULA",
        "CARGO",
        "ACCIONES",
      ],
      content: [
        {
          ID: "1ID",
          NOMBRE: "1NOMBRE",
          CORREO: "1CORREO",
          CELULAR: "1CELULAR",
          CÉDULA: "1CÉDULA",
          CARGO: "1CARGO",
          ACCIONES: "1ACCIONES",
          CORREO: "1CORREO",
          CELULAR: "1CELULAR",
          CÉDULA: "1CÉDULA",
          CARGO: "1CARGO",
          ACCIONES: "1ACCIONES",
        },
        {
          ID: "2ID",
          NOMBRE: "2NOMBRE",
          CORREO: "2CORREO",
          CELULAR: "2CELULAR",
          CÉDULA: "2CÉDULA",
          CARGO: "2CARGO",
          ACCIONES: "2ACCIONES",
          CORREO: "2CORREO",
          CELULAR: "2CELULAR",
          CÉDULA: "2CÉDULA",
          CARGO: "2CARGO",
          ACCIONES: "2ACCIONES",
        },
        {
          ID: "3ID",
          NOMBRE: "3NOMBRE",
          CORREO: "3CORREO",
          CELULAR: "3CELULAR",
          CÉDULA: "3CÉDULA",
          CARGO: "3CARGO",
          ACCIONES: "3ACCIONES",
          CORREO: "3CORREO",
          CELULAR: "3CELULAR",
          CÉDULA: "3CÉDULA",
          CARGO: "3CARGO",
          ACCIONES: "3ACCIONES",
        },
        {
          ID: "4ID",
          NOMBRE: "4NOMBRE",
          CORREO: "4CORREO",
          CELULAR: "4CELULAR",
          CÉDULA: "4CÉDULA",
          CARGO: "4CARGO",
          ACCIONES: "4ACCIONES",
          CORREO: "4CORREO",
          CELULAR: "4CELULAR",
          CÉDULA: "4CÉDULA",
          CARGO: "4CARGO",
          ACCIONES: "4ACCIONES",
        },
        {
          ID: "5ID",
          NOMBRE: "5NOMBRE",
          CORREO: "5CORREO",
          CELULAR: "5CELULAR",
          CÉDULA: "5CÉDULA",
          CARGO: "5CARGO",
          ACCIONES: "5ACCIONES",
          CORREO: "5CORREO",
          CELULAR: "5CELULAR",
          CÉDULA: "5CÉDULA",
          CARGO: "5CARGO",
          ACCIONES: "5ACCIONES",
        },
        {
          ID: "6ID",
          NOMBRE: "6NOMBRE",
          CORREO: "6CORREO",
          CELULAR: "6CELULAR",
          CÉDULA: "6CÉDULA",
          CARGO: "6CARGO",
          ACCIONES: "6ACCIONES",
          CORREO: "6CORREO",
          CELULAR: "6CELULAR",
          CÉDULA: "6CÉDULA",
          CARGO: "6CARGO",
          ACCIONES: "6ACCIONES",
        },
        {
          ID: "7ID",
          NOMBRE: "7NOMBRE",
          CORREO: "7CORREO",
          CELULAR: "7CELULAR",
          CÉDULA: "7CÉDULA",
          CARGO: "7CARGO",
          ACCIONES: "7ACCIONES",
          CORREO: "7CORREO",
          CELULAR: "7CELULAR",
          CÉDULA: "7CÉDULA",
          CARGO: "7CARGO",
          ACCIONES: "7ACCIONES",
        },
        {
          ID: "8ID",
          NOMBRE: "8NOMBRE",
          CORREO: "8CORREO",
          CELULAR: "8CELULAR",
          CÉDULA: "8CÉDULA",
          CARGO: "8CARGO",
          ACCIONES: "8ACCIONES",
          CORREO: "8CORREO",
          CELULAR: "8CELULAR",
          CÉDULA: "8CÉDULA",
          CARGO: "8CARGO",
          ACCIONES: "8ACCIONES",
        },
        {
          ID: "9ID",
          NOMBRE: "9NOMBRE",
          CORREO: "9CORREO",
          CELULAR: "9CELULAR",
          CÉDULA: "9CÉDULA",
          CARGO: "9CARGO",
          ACCIONES: "9ACCIONES",
          CORREO: "9CORREO",
          CELULAR: "9CELULAR",
          CÉDULA: "9CÉDULA",
          CARGO: "9CARGO",
          ACCIONES: "9ACCIONES",
        },
        {
          ID: "10ID",
          NOMBRE: "10NOMBRE",
          CORREO: "10CORREO",
          CELULAR: "10CELULAR",
          CÉDULA: "10CÉDULA",
          CARGO: "10CARGO",
          ACCIONES: "10ACCIONES",
          CORREO: "10CORREO",
          CELULAR: "10CELULAR",
          CÉDULA: "10CÉDULA",
          CARGO: "10CARGO",
          ACCIONES: "10ACCIONES",
        },
        {
          ID: "11ID",
          NOMBRE: "11NOMBRE",
          CORREO: "11CORREO",
          CELULAR: "11CELULAR",
          CÉDULA: "11CÉDULA",
          CARGO: "11CARGO",
          ACCIONES: "11ACCIONES",
          CORREO: "11CORREO",
          CELULAR: "11CELULAR",
          CÉDULA: "11CÉDULA",
          CARGO: "11CARGO",
          ACCIONES: "11ACCIONES",
        },
        {
          ID: "12ID",
          NOMBRE: "12NOMBRE",
          CORREO: "12CORREO",
          CELULAR: "12CELULAR",
          CÉDULA: "12CÉDULA",
          CARGO: "12CARGO",
          ACCIONES: "12ACCIONES",
          CORREO: "12CORREO",
          CELULAR: "12CELULAR",
          CÉDULA: "12CÉDULA",
          CARGO: "12CARGO",
          ACCIONES: "12ACCIONES",
        },
        {
          ID: "13ID",
          NOMBRE: "13NOMBRE",
          CORREO: "13CORREO",
          CELULAR: "13CELULAR",
          CÉDULA: "13CÉDULA",
          CARGO: "13CARGO",
          ACCIONES: "13ACCIONES",
          CORREO: "13CORREO",
          CELULAR: "13CELULAR",
          CÉDULA: "13CÉDULA",
          CARGO: "13CARGO",
          ACCIONES: "13ACCIONES",
        },
        {
          ID: "14ID",
          NOMBRE: "14NOMBRE",
          CORREO: "14CORREO",
          CELULAR: "14CELULAR",
          CÉDULA: "14CÉDULA",
          CARGO: "14CARGO",
          ACCIONES: "14ACCIONES",
          CORREO: "14CORREO",
          CELULAR: "14CELULAR",
          CÉDULA: "14CÉDULA",
          CARGO: "14CARGO",
          ACCIONES: "14ACCIONES",
        },
        {
          ID: "15ID",
          NOMBRE: "15NOMBRE",
          CORREO: "15CORREO",
          CELULAR: "15CELULAR",
          CÉDULA: "15CÉDULA",
          CARGO: "15CARGO",
          ACCIONES: "15ACCIONES",
          CORREO: "15CORREO",
          CELULAR: "15CELULAR",
          CÉDULA: "15CÉDULA",
          CARGO: "15CARGO",
          ACCIONES: "15ACCIONES",
        },
        {
          ID: "16ID",
          NOMBRE: "16NOMBRE",
          CORREO: "16CORREO",
          CELULAR: "16CELULAR",
          CÉDULA: "16CÉDULA",
          CARGO: "16CARGO",
          ACCIONES: "16ACCIONES",
          CORREO: "16CORREO",
          CELULAR: "16CELULAR",
          CÉDULA: "16CÉDULA",
          CARGO: "16CARGO",
          ACCIONES: "16ACCIONES",
        },
        {
          ID: "17ID",
          NOMBRE: "17NOMBRE",
          CORREO: "17CORREO",
          CELULAR: "17CELULAR",
          CÉDULA: "17CÉDULA",
          CARGO: "17CARGO",
          ACCIONES: "17ACCIONES",
          CORREO: "17CORREO",
          CELULAR: "17CELULAR",
          CÉDULA: "17CÉDULA",
          CARGO: "17CARGO",
          ACCIONES: "17ACCIONES",
        },
        {
          ID: "18ID",
          NOMBRE: "18NOMBRE",
          CORREO: "18CORREO",
          CELULAR: "18CELULAR",
          CÉDULA: "18CÉDULA",
          CARGO: "18CARGO",
          ACCIONES: "18ACCIONES",
          CORREO: "18CORREO",
          CELULAR: "18CELULAR",
          CÉDULA: "18CÉDULA",
          CARGO: "18CARGO",
          ACCIONES: "18ACCIONES",
        },
        {
          ID: "19ID",
          NOMBRE: "19NOMBRE",
          CORREO: "19CORREO",
          CELULAR: "19CELULAR",
          CÉDULA: "19CÉDULA",
          CARGO: "19CARGO",
          ACCIONES: "19ACCIONES",
          CORREO: "19CORREO",
          CELULAR: "19CELULAR",
          CÉDULA: "19CÉDULA",
          CARGO: "19CARGO",
          ACCIONES: "19ACCIONES",
        },
        {
          ID: "20ID",
          NOMBRE: "20NOMBRE",
          CORREO: "20CORREO",
          CELULAR: "20CELULAR",
          CÉDULA: "20CÉDULA",
          CARGO: "20CARGO",
          ACCIONES: "20ACCIONES",
          CORREO: "20CORREO",
          CELULAR: "20CELULAR",
          CÉDULA: "20CÉDULA",
          CARGO: "20CARGO",
          ACCIONES: "20ACCIONES",
        },
        {
          ID: "21ID",
          NOMBRE: "21NOMBRE",
          CORREO: "21CORREO",
          CELULAR: "21CELULAR",
          CÉDULA: "21CÉDULA",
          CARGO: "21CARGO",
          ACCIONES: "21ACCIONES",
          CORREO: "21CORREO",
          CELULAR: "21CELULAR",
          CÉDULA: "21CÉDULA",
          CARGO: "21CARGO",
          ACCIONES: "21ACCIONES",
        },
        {
          ID: "22ID",
          NOMBRE: "22NOMBRE",
          CORREO: "22CORREO",
          CELULAR: "22CELULAR",
          CÉDULA: "22CÉDULA",
          CARGO: "22CARGO",
          ACCIONES: "22ACCIONES",
          CORREO: "22CORREO",
          CELULAR: "22CELULAR",
          CÉDULA: "22CÉDULA",
          CARGO: "22CARGO",
          ACCIONES: "22ACCIONES",
        },
        {
          ID: "23ID",
          NOMBRE: "23NOMBRE",
          CORREO: "23CORREO",
          CELULAR: "23CELULAR",
          CÉDULA: "23CÉDULA",
          CARGO: "23CARGO",
          ACCIONES: "23ACCIONES",
          CORREO: "23CORREO",
          CELULAR: "23CELULAR",
          CÉDULA: "23CÉDULA",
          CARGO: "23CARGO",
          ACCIONES: "23ACCIONES",
        },
        {
          ID: "24ID",
          NOMBRE: "24NOMBRE",
          CORREO: "24CORREO",
          CELULAR: "24CELULAR",
          CÉDULA: "24CÉDULA",
          CARGO: "24CARGO",
          ACCIONES: "24ACCIONES",
          CORREO: "24CORREO",
          CELULAR: "24CELULAR",
          CÉDULA: "24CÉDULA",
          CARGO: "24CARGO",
          ACCIONES: "24ACCIONES",
        },
        {
          ID: "25ID",
          NOMBRE: "25NOMBRE",
          CORREO: "25CORREO",
          CELULAR: "25CELULAR",
          CÉDULA: "25CÉDULA",
          CARGO: "25CARGO",
          ACCIONES: "25ACCIONES",
          CORREO: "25CORREO",
          CELULAR: "25CELULAR",
          CÉDULA: "25CÉDULA",
          CARGO: "25CARGO",
          ACCIONES: "25ACCIONES",
        },
        {
          ID: "26ID",
          NOMBRE: "26NOMBRE",
          CORREO: "26CORREO",
          CELULAR: "26CELULAR",
          CÉDULA: "26CÉDULA",
          CARGO: "26CARGO",
          ACCIONES: "26ACCIONES",
          CORREO: "26CORREO",
          CELULAR: "26CELULAR",
          CÉDULA: "26CÉDULA",
          CARGO: "26CARGO",
          ACCIONES: "26ACCIONES",
        },
        {
          ID: "27ID",
          NOMBRE: "27NOMBRE",
          CORREO: "27CORREO",
          CELULAR: "27CELULAR",
          CÉDULA: "27CÉDULA",
          CARGO: "27CARGO",
          ACCIONES: "27ACCIONES",
          CORREO: "27CORREO",
          CELULAR: "27CELULAR",
          CÉDULA: "27CÉDULA",
          CARGO: "27CARGO",
          ACCIONES: "27ACCIONES",
        },
        {
          ID: "28ID",
          NOMBRE: "28NOMBRE",
          CORREO: "28CORREO",
          CELULAR: "28CELULAR",
          CÉDULA: "28CÉDULA",
          CARGO: "28CARGO",
          ACCIONES: "28ACCIONES",
          CORREO: "28CORREO",
          CELULAR: "28CELULAR",
          CÉDULA: "28CÉDULA",
          CARGO: "28CARGO",
          ACCIONES: "28ACCIONES",
        },
      ],
    };
  },
};
</script>

<style scoped>
.admin-employee {
  width: 100%;
  height: 100%;
  background-color: var(--color2);
  color: var(--color7);
  display: grid;
  grid-template-rows: 10% 90%;
}
.admin-employee div:nth-child(1) {
  display: flex;
  justify-content: space-around;
  align-items: center;
}
#add-button {
  height: fit-content;
  padding: 8px;
  cursor: pointer;
  border-radius: 16px;
  border-width: 1px;
  background-color: var(--color1);
}
</style>
